### ISSUE TITLE
checklist of updates to make for major version update to this project

### ISSUE THREAD

**Issue by cyberboy666** [gaeljaton/Sync-Ope---analog-video-sync-stripper-injector-mixer#4]
im making the first _major_ version update for any  __underscores__ project here for sync_ope:

gonna replace the current ac-ac power-supply input circuit with a single supply 12v one. this is a large enough change that i should also update:

- [x] circuit price
- [ ] ~~the shop photo of circuit~~ decided this is not needed
- [ ] ~~the doodle sketch~~ decided this is not needed
- [x] the booklet
- [x] the 3d rendered image
- [x] the video-walkthrough
- [ ] anything else ?

other things (that should update every release not just major):

- [ ] release version in git
- [ ] bom - tayda/mouser/both/interactive
- [ ] schematic
- [ ] gerber zip
- [ ] diy parts sheet (this wil be manual)

**Comment by cyberboy666** [comment]
![image](https://user-images.githubusercontent.com/12017938/203668142-027da754-8c44-4d19-bb09-65ff3e721088.png)

**Comment by cyberboy666** [comment]
#5
